### Config.yaml to set wildcards to Snakefile ###

workdir: # path/to/working_directory

sampled_protocols: sampled_protocols.tsv # don't edit this line !

resolutions: # resolution of interest i.e. [200000,50000,25000,10000]

chromosomes: # full chromosomes to adjust without contig i.e. [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, X]

regions: # regions of interest i.e. ['1-158534110', '1000000-6000000', '1000000-3000000', '1500000-3500000', '2000000-3000000', '2200000-2800000']

samples: # samples who matched with sample column of sampled_protocols i.e. [trio1.offspring, trio1.father, trio1.mother, trio2.offspring, trio2.mother, trio2.father]
