
import os
import glob
import re
import pandas as pd


# Function definition
def set_run_names(protocols):
    ''' For each protocol retrieve the associated run names '''
    runs = []
    for protocol in protocols.index:
        matrix_dir = protocols.loc[protocol]['matrixdir']
        prot_runs = []
        for f in glob.glob(matrix_dir+'/*.matrix'):
            prot_runs.append(re.sub('_\d+.matrix', '', os.path.basename(f),))
        runs.append(",".join(set(prot_runs)))
    protocols['runs'] = runs
    return protocols


def get_raw_matrix(wildcards):
    """ input function for rule conversion
        returns the hicpro raw matrix associated to a protocol-run-resolution
    """
    mdir = sampled_protocols.loc[(wildcards.sample, wildcards.protocol)]['matrixdir']
    matrix_file = wildcards.run + "_" + wildcards.resolution + ".matrix"
    return mdir + "/" + matrix_file


def get_bed_file(wildcards):
    """ input function for rule conversion
        returns the hicpro bed file associated to a protocol-run-resolution
    """
    mdir = sampled_protocols.loc[(wildcards.sample, wildcards.protocol)]['matrixdir']
    bed_file = wildcards.run + "_" + wildcards.resolution + "_abs.bed"
    return mdir + "/" + bed_file


def get_matrices(wildcards):
    """ input function for rule mergeprotocol
        returns list of the h5 matrices associated with a protocol-resolution
    """
    runs = sampled_protocols.loc[(wildcards.sample, wildcards.protocol)]['runs'].split(',')
    matrices = []
    for run in runs:
        m = run + "_" + wildcards.resolution + ".h5"
        m_path = os.path.join("hdf5", wildcards.sample, wildcards.protocol, m)
        matrices.append(m_path)
    return matrices

def get_merged_matrices(wildcards):
    """ input function for rule merged
        return list of the merged h5 matrices from rule mergeprotocol from a association individual-resolution
    """
    matrices = []
    for prot in sampled_protocols['protocol']:
        if prot in sampled_protocols.loc[wildcards.sample]['protocol']:
            m_path = os.path.join("hdf5", wildcards.sample, prot, wildcards.resolution, "matrix.h5")
            matrices.append(m_path)
    return matrices


configfile: "config.yaml"

sampled_protocols = pd.read_csv(config["sampled_protocols"], sep = "\t").set_index(["sample","protocol"], drop = False)

sampled_protocols = set_run_names(sampled_protocols)

chromosomes = config['chromosomes']
resolutions = config['resolutions']
regions = config['regions']

protocols_and_merged = list(set(sampled_protocols['protocol'])) + ['Merged']

workdir: config['workdir']

samples = config['samples']

wildcard_constraints:
    protocol="|".join(protocols_and_merged)

rule all:
        input:
            expand("plots/{sample}/merged/{resolution}/{region}_plot.png", sample=samples, protocol=protocols_and_merged, resolution=resolutions, region=regions),

rule conversion:
    input:
        raw = get_raw_matrix,
        bed = get_bed_file
    output:
        "hdf5/{sample}/{protocol}/{run}_{resolution}.h5"
    shell:
        "hicConvertFormat --matrices {input.raw} --bedFileHicpro {input.bed}"
        " --outFileName {output} --outputFormat h5 --inputFormat hicpro"

rule mergeprotocol:
    input:
        get_matrices
    output:
        "hdf5/{sample}/{protocol}/{resolution}/matrix.h5"
    shell:
        "hicSumMatrices --matrices  {input} --outFileName {output}"

rule merge:
    input:
        # expand("hdf5/{{sample}}/{unit.protocol}/{{resolution}}/matrix.h5", unit=sampled_protocols.itertuples())
        get_merged_matrices
    output:
        "hdf5/{sample}/merged/{resolution}/matrix.h5"
    shell:
        "hicSumMatrices --matrices {input} --outFileName {output}"

rule adjust:
    input:
        "hdf5/{sample}/merged/{resolution}/matrix.h5",
    output:
        "hdf5/{sample}/merged/{resolution}/adjusted.h5"
    params:
        chromosomes = chromosomes
    shell:
        "hicAdjustMatrix --matrix {input} --outFileName {output} "
        " --chromosomes {params.chromosomes} --action keep ;"

rule normalize:
    input:
        "hdf5/{sample}/merged/{resolution}/adjusted.h5"
    output:
        "hdf5/{sample}/merged/{resolution}/normalized.h5"
    shell:
        "hicNormalize --matrices {input} --outFileName {output}"
        " --normalize smallest"

rule correct:
    input:
        "hdf5/{sample}/merged/{resolution}/normalized.h5"
    output:
        "hdf5/{sample}/merged/{resolution}/corrected.h5"
    shell:
        "hicCorrectMatrix correct --matrix {input} --outFileName {output}"

rule diagnostic:
    input:
        "hdf5/{sample}/merged/{resolution}/{type}.h5"
    output:
        "hdf5/{sample}/merged/{resolution}/{type}_diagnostic.png"
    shell:
        "hicCorrectMatrix diagnostic_plot -m {input} -o {output}"

rule plotMatrix:
    input:
        "hdf5/{sample}/merged/{resolution}/corrected.h5"
    output:
        "plots/{sample}/merged/{resolution}/{region}_plot.png"
    shell:
        "hicPlotMatrix --matrix {input} --outFileName {output} --region {wildcards.region} --log"
