

units: units.tsv
protocols: protocols.tsv

ref:
  name: ARS-UCD1.2
  # Path to the reference genome and associater bowtie indexes
  genome: /bank/bowtie2db/ensembl_bos_taurus_genome
  chromosome_size: /work2/genphyse/dynagen/tfaraut/polledHiC/data/genome/chrom.len

hicpro:
  Maison:
    restriction_site: 'A^AGCTT'
    ligation_site: 'AAGCTAGCTT'
  Arima:
    restriction_site: '^GATC,G^ANTC'
    ligation_site: 'GATCGATC,GANTGATC,GANTANTC,GATCANTC'
  Dovetail:
    restriction_site: '^GATC'
    ligation_site: 'GATCGATC'
  bin_size: '200000,50000,25000,10000'

sample: nfcoreout

readroot: /work2/genphyse/dynagen/tfaraut/polledHiC/data/data/snaketest
